// public/src/components/Sidebar.vue
<template>
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/" class="brand-link logo-switch">
      <img src="https://adminlte.io/docs/3.1//assets/img/logo-xl.png" alt="AdminLTE Logo" class="brand-image-xs logo-xl" style="left: 12px" />
    </a>

    <nav class="sidebar">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
        <li class="nav-item" v-for="(item, index) in items" :key="`menu-item-${index}`">
          <router-link :to="`/list/${item}`" :class="`nav-link ${$route.params.resource === item? 'active': ''}`">{{ item }}</router-link>
        </li>
      </ul>
    </nav>
  </aside>
</template>

<script>
module.exports = {
  data() {
    return {
      items: [],
    };
  },

  async mounted() {
    const data = (await axios.get('/api/monedb/@schemes')).data;
    this.items = data.map(e => e.name);
  },
}
</script>

// public/src/Sidebar.jsx
const Sidebar = props => {
  const [menuItems, setMenuItems] = React.useState([]);

  /**
   * Get menu items from MoneDB.@validators[].target
   */
  React.useEffect(() => {
    (async () => {
      const data = (await axios.get('/api/monedb/@validators')).data;
      setMenuItems(data.map(e => e.target));
    })();
  }, []);

  return (
    <aside className="main-sidebar sidebar-dark-primary elevation-4">
      <a href="/" className="brand-link logo-switch">
        <img src="https://adminlte.io/docs/3.1//assets/img/logo-xl.png" alt="AdminLTE Logo" className="brand-image-xs logo-xl" style={{left: '12px'}} />
      </a>

      <nav className="sidebar">
        <ul className="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
          {
            menuItems.map((item, index) => (
              <li className="nav-item" key={`menuitem-${index}`}>
                <a href="#" className="nav-link active">{item}</a>
              </li>
            ))
          }
        </ul>
      </nav>
    </aside>
  );
};
